---
stages:
  - test

default:
  image: gentoo/stage3:latest
  services:
    - gentoo/portage:latest
  before_script:
    - emerge --quiet dev-util/pkgcheck

pkgcheck:
  stage: test
  tags:
    - portage
  script:
    - echo "Revisando ebuilds..."
    - pkgcheck scan
    - echo "No se encontraron problemas en ebuilds."

