---
stages:
  - test

pkgcheck:
  stage: test
  tags:
    - portage
  image: gentoo/stage3:latest
  before_script:
    - emerge --quiet dev-util/pkgcheck
  script:
    - echo "Revisando ebuilds..."
    - pkgcheck scan
    - echo "No se encontraron problemas en ebuilds."
